# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anno_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(339, 302)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setMinimumSize(QtCore.QSize(0, 30))
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setMinimumSize(QtCore.QSize(6, 0))
        self.label_2.setMaximumSize(QtCore.QSize(6, 16777215))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.checkBox_visible = QtWidgets.QCheckBox(self.widget)
        self.checkBox_visible.setMinimumSize(QtCore.QSize(0, 25))
        self.checkBox_visible.setMaximumSize(QtCore.QSize(120, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.checkBox_visible.setFont(font)
        self.checkBox_visible.setObjectName("checkBox_visible")
        self.horizontalLayout.addWidget(self.checkBox_visible)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.comboBox_group_select = QtWidgets.QComboBox(self.widget)
        self.comboBox_group_select.setMinimumSize(QtCore.QSize(60, 25))
        self.comboBox_group_select.setMaximumSize(QtCore.QSize(60, 25))
        self.comboBox_group_select.setObjectName("comboBox_group_select")
        self.horizontalLayout.addWidget(self.comboBox_group_select)
        self.button_prev_group = QtWidgets.QPushButton(self.widget)
        self.button_prev_group.setMinimumSize(QtCore.QSize(25, 25))
        self.button_prev_group.setMaximumSize(QtCore.QSize(25, 25))
        self.button_prev_group.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/left_32.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_prev_group.setIcon(icon)
        self.button_prev_group.setObjectName("button_prev_group")
        self.horizontalLayout.addWidget(self.button_prev_group)
        self.button_next_group = QtWidgets.QPushButton(self.widget)
        self.button_next_group.setMinimumSize(QtCore.QSize(25, 25))
        self.button_next_group.setMaximumSize(QtCore.QSize(25, 25))
        self.button_next_group.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/right_32.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_next_group.setIcon(icon1)
        self.button_next_group.setObjectName("button_next_group")
        self.horizontalLayout.addWidget(self.button_next_group)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(3, 0))
        self.label.setMaximumSize(QtCore.QSize(3, 16777215))
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.listWidget_annos = QtWidgets.QListWidget(Form)
        self.listWidget_annos.setStyleSheet("")
        self.listWidget_annos.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.listWidget_annos.setObjectName("listWidget_annos")
        self.verticalLayout.addWidget(self.listWidget_annos)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_3.setText(_translate("Form", "Annos"))
        self.checkBox_visible.setText(_translate("Form", "Visible"))
