# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\PycharmProjects\ISAT_with_segment_anything\ISAT\ui\stats_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1280, 720)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_dir = QtWidgets.QHBoxLayout()
        self.horizontalLayout_dir.setObjectName("horizontalLayout_dir")
        self.label_dir = QtWidgets.QLabel(Dialog)
        self.label_dir.setObjectName("label_dir")
        self.horizontalLayout_dir.addWidget(self.label_dir)
        self.lineEdit_dir = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dir.setObjectName("lineEdit_dir")
        self.horizontalLayout_dir.addWidget(self.lineEdit_dir)
        self.pushButton_browse = QtWidgets.QPushButton(Dialog)
        self.pushButton_browse.setObjectName("pushButton_browse")
        self.horizontalLayout_dir.addWidget(self.pushButton_browse)
        self.verticalLayout.addLayout(self.horizontalLayout_dir)
        self.label_status = QtWidgets.QLabel(Dialog)
        self.label_status.setText("")
        self.label_status.setObjectName("label_status")
        self.verticalLayout.addWidget(self.label_status)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.verticalLayout.addWidget(self.tableWidget)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.horizontalLayout_option = QtWidgets.QHBoxLayout()
        self.horizontalLayout_option.setObjectName("horizontalLayout_option")
        self.checkBox_recursive = QtWidgets.QCheckBox(Dialog)
        self.checkBox_recursive.setObjectName("checkBox_recursive")
        self.horizontalLayout_option.addWidget(self.checkBox_recursive)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_option.addItem(spacerItem)
        self.pushButton_start = QtWidgets.QPushButton(Dialog)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_option.addWidget(self.pushButton_start)
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setEnabled(False)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_option.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_option)
        self.label_summary = QtWidgets.QLabel(Dialog)
        self.label_summary.setText("")
        self.label_summary.setObjectName("label_summary")
        self.verticalLayout.addWidget(self.label_summary)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Annotation Statistics"))
        self.label_dir.setText(_translate("Dialog", "Label directory:"))
        self.lineEdit_dir.setPlaceholderText(_translate("Dialog", "Directory that contains the ISAT label json files"))
        self.pushButton_browse.setText(_translate("Dialog", "Browse..."))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Category"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Polygons"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "OBB"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Total"))
        self.checkBox_recursive.setText(_translate("Dialog", "Include subdirectories"))
        self.pushButton_start.setText(_translate("Dialog", "Start"))
        self.pushButton_cancel.setText(_translate("Dialog", "Cancel"))
