# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/lg/disk2/PycharmProjects/ISAT_with_segment_anything/ISAT/ui/text_prompt_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(285, 134)
        Form.setMinimumSize(QtCore.QSize(285, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tabWidget = QtWidgets.QTabWidget(self.widget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.tab)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_prompt_text_for_single_category = QtWidgets.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.lineEdit_prompt_text_for_single_category.setFont(font)
        self.lineEdit_prompt_text_for_single_category.setText("")
        self.lineEdit_prompt_text_for_single_category.setObjectName("lineEdit_prompt_text_for_single_category")
        self.horizontalLayout.addWidget(self.lineEdit_prompt_text_for_single_category)
        self.pushButton_predict_for_single_category = QtWidgets.QPushButton(self.tab)
        self.pushButton_predict_for_single_category.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_predict_for_single_category.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_predict_for_single_category.setFont(font)
        self.pushButton_predict_for_single_category.setObjectName("pushButton_predict_for_single_category")
        self.horizontalLayout.addWidget(self.pushButton_predict_for_single_category)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_catgories_setting = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_catgories_setting.setObjectName("pushButton_catgories_setting")
        self.horizontalLayout_4.addWidget(self.pushButton_catgories_setting)
        self.pushButton_predict_for_multi_categoriies = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_predict_for_multi_categoriies.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_predict_for_multi_categoriies.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_predict_for_multi_categoriies.setObjectName("pushButton_predict_for_multi_categoriies")
        self.horizontalLayout_4.addWidget(self.pushButton_predict_for_multi_categoriies)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout_3.addWidget(self.tabWidget)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_num_objects = QtWidgets.QLabel(self.widget_2)
        self.label_num_objects.setMinimumSize(QtCore.QSize(24, 0))
        self.label_num_objects.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_num_objects.setObjectName("label_num_objects")
        self.horizontalLayout_2.addWidget(self.label_num_objects)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 10))
        self.progressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"            border: 1px solid #888783;\n"
"\n"
"            border-radius: 3px;\n"
"        }\n"
"QProgressBar::chunk {\n"
"            background-color: #74d65f;\n"
"            border-radius: 2px;\n"
"            width: 6px;\n"
"            margin: 1px;\n"
"        }")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Texr prompt"))
        self.lineEdit_prompt_text_for_single_category.setPlaceholderText(_translate("Form", "Only english is supported."))
        self.pushButton_predict_for_single_category.setText(_translate("Form", "Predict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Single category"))
        self.pushButton_catgories_setting.setText(_translate("Form", "Categories setting"))
        self.pushButton_predict_for_multi_categoriies.setText(_translate("Form", "Predict"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Multiple categories"))
        self.label.setText(_translate("Form", "Found"))
        self.label_num_objects.setText(_translate("Form", "......"))
        self.label_3.setText(_translate("Form", "object(s)"))
