# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/lg/disk2/PycharmProjects/ISAT_with_segment_anything/ISAT/ui/text_prompt_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(349, 60)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_prompt_text = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_prompt_text.setText("")
        self.lineEdit_prompt_text.setObjectName("lineEdit_prompt_text")
        self.horizontalLayout.addWidget(self.lineEdit_prompt_text)
        self.pushButton_predict = QtWidgets.QPushButton(self.widget)
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.horizontalLayout.addWidget(self.pushButton_predict)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Texr prompt"))
        self.lineEdit_prompt_text.setPlaceholderText(_translate("Form", "Prompt text"))
        self.pushButton_predict.setText(_translate("Form", "Predict"))
