# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/lg/PycharmProjects/ISAT_with_segment_anything/ISAT/ui/video_to_frames.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1000, 680)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_video_path = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_video_path.setObjectName("lineEdit_video_path")
        self.horizontalLayout_2.addWidget(self.lineEdit_video_path)
        self.pushButton_video_path = QtWidgets.QPushButton(self.widget)
        self.pushButton_video_path.setObjectName("pushButton_video_path")
        self.horizontalLayout_2.addWidget(self.pushButton_video_path)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Dialog)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit_frames_root = QtWidgets.QLineEdit(self.widget_2)
        self.lineEdit_frames_root.setObjectName("lineEdit_frames_root")
        self.horizontalLayout.addWidget(self.lineEdit_frames_root)
        self.pushButton_frames_root = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_frames_root.setObjectName("pushButton_frames_root")
        self.horizontalLayout.addWidget(self.pushButton_frames_root)
        self.verticalLayout.addWidget(self.widget_2)
        self.textBrowser = QtWidgets.QTextBrowser(Dialog)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.widget_3 = QtWidgets.QWidget(Dialog)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(893, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.pushButton_start = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_3.addWidget(self.pushButton_start)
        self.verticalLayout.addWidget(self.widget_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Video to frames"))
        self.lineEdit_video_path.setPlaceholderText(_translate("Dialog", "video path"))
        self.pushButton_video_path.setText(_translate("Dialog", "video path"))
        self.lineEdit_frames_root.setPlaceholderText(_translate("Dialog", "frames save root"))
        self.pushButton_frames_root.setText(_translate("Dialog", "save root"))
        self.pushButton_start.setText(_translate("Dialog", "start"))
