# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/media/lg/disk2/PycharmProjects/ISAT_with_segment_anything/ISAT/ui/visual_prompt_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(285, 65)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(285, 0))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(6, 6, 6, 6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_positive_box = QtWidgets.QPushButton(self.widget)
        self.pushButton_positive_box.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_positive_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_positive_box.setObjectName("pushButton_positive_box")
        self.horizontalLayout.addWidget(self.pushButton_positive_box)
        self.pushButton_negative_box = QtWidgets.QPushButton(self.widget)
        self.pushButton_negative_box.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_negative_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pushButton_negative_box.setObjectName("pushButton_negative_box")
        self.horizontalLayout.addWidget(self.pushButton_negative_box)
        self.pushButton_predict = QtWidgets.QPushButton(self.widget)
        self.pushButton_predict.setMinimumSize(QtCore.QSize(80, 0))
        self.pushButton_predict.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton_predict.setObjectName("pushButton_predict")
        self.horizontalLayout.addWidget(self.pushButton_predict)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(Form)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_num_objects = QtWidgets.QLabel(self.widget_2)
        self.label_num_objects.setMinimumSize(QtCore.QSize(24, 0))
        self.label_num_objects.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_num_objects.setObjectName("label_num_objects")
        self.horizontalLayout_2.addWidget(self.label_num_objects)
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Visual prompt"))
        self.pushButton_positive_box.setText(_translate("Form", "Positive box"))
        self.pushButton_negative_box.setText(_translate("Form", "Negative box"))
        self.pushButton_predict.setText(_translate("Form", "Predict"))
        self.label.setText(_translate("Form", "Found"))
        self.label_num_objects.setText(_translate("Form", "......"))
        self.label_3.setText(_translate("Form", "object(s)"))
