# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'category_dock.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(231, 462)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(3, 0, -1, 3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_group_mode = QtWidgets.QPushButton(Form)
        self.pushButton_group_mode.setObjectName("pushButton_group_mode")
        self.horizontalLayout.addWidget(self.pushButton_group_mode)
        self.pushButton_decrease = QtWidgets.QPushButton(Form)
        self.pushButton_decrease.setObjectName("pushButton_decrease")
        self.horizontalLayout.addWidget(self.pushButton_decrease)
        self.lineEdit_currentGroup = QtWidgets.QLineEdit(Form)
        self.lineEdit_currentGroup.setObjectName("lineEdit_currentGroup")
        self.horizontalLayout.addWidget(self.lineEdit_currentGroup)
        self.pushButton_increase = QtWidgets.QPushButton(Form)
        self.pushButton_increase.setObjectName("pushButton_increase")
        self.horizontalLayout.addWidget(self.pushButton_increase)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_group_mode.setText(_translate("Form", "Auto"))
        self.pushButton_decrease.setText(_translate("Form", "-"))
        self.pushButton_increase.setText(_translate("Form", "+"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
